Estimate heat demand for archetypes my room
nestauk/asf_heat_pump_affordability pull request #17
Opened 2024-02-28 10:41 UTC by danlewis85

---

# Description

Please review the notebook 'Archetype_Heat_Demand.py' - it aims to provide guidance for the annual heat demand of archetypes in a way that is compatible with the costs estimated elsewhere. As such, it provides a median estimated heat demand for archetypes adjusted by number of habitable rooms, using the same room values as the costs model.

# Instructions for Reviewer

In order to test the code in this PR you need to use jupytext to convert asf_heat_pump_affordability/notebooks/Archetype_Heat_Demand.py into a notebook that you can run. 

Please pay special attention to the final table, which is the result to be shared.

# Checklist:

- [ ] I have refactored my code out from `notebooks/`
- [ x] I have checked the code runs
- [ x] I have tested the code
- [ x] I have run `pre-commit` and addressed any issues not automatically fixed
- [ x] I have merged any new changes from `dev`
- [ ~] I have documented the code
  - [ ] Major functions have docstrings
  - [ ] Appropriate information has been added to `README`s
- [ x] I have explained this PR above
- [ x] I have requested a code review

2024-02-28 17:10 UTC, crispy-wonton requested changes, later dismissed
Code makes sense and looks mostly good.

There are a couple of minor errors, and I've made a couple of suggestions to increase the robustness of the code. I also left a question on pseudo R-squared.

2024-02-28 17:10 UTC, crispy-wonton commented on asf_heat_pump_affordability/notebooks/Archetype_Heat_Demand.py
> +model = sm.quantreg("heat_demand ~ archetype + NUMBER_HABITABLE_ROOMS", data=data).fit(
Why does model.summary() give a pseudo R-squared instead of just [adjusted] R-squared? I understand that pseudo R-squared is calculated when you have categorical or discrete target variable (?) but that's not the case here.

2024-02-28 17:10 UTC, crispy-wonton commented on asf_heat_pump_affordability/notebooks/Archetype_Heat_Demand.py
> +        NUMBER_HABITABLE_ROOMS=list(numpy.linspace(0, 12, 13)) * 8,
Don't think we need to predict for properties with zero rooms
```suggestion
                "archetype": [
                    label
                    for labels in [[archetype] * 12 for archetype in quantiles.index]
                    for label in labels
                ],
                "NUMBER_HABITABLE_ROOMS": list(numpy.linspace(1, 12, 12)) * 8,
            }
        )
    )
    .summary_frame()
    .assign(
        archetype=[
            label
            for labels in [[archetype] * 12 for archetype in quantiles.index]
            for label in labels
        ],
        NUMBER_HABITABLE_ROOMS=list(numpy.linspace(1, 12, 12)) * 8,
```

2024-02-28 17:10 UTC, crispy-wonton commented on asf_heat_pump_affordability/notebooks/Archetype_Heat_Demand.py
> +ax.set_xlabel("Total Floor Area (m2)")
```suggestion
ax.set_xlabel("Number of rooms")
```

2024-02-28 17:10 UTC, crispy-wonton commented on asf_heat_pump_affordability/notebooks/Archetype_Heat_Demand.py
> +        NUMBER_HABITABLE_ROOMS=list(numpy.linspace(0, 12, 13)) * 8,
Same as above for 0 rooms. Also, you could define your list of archetypes and number of rooms once then only need to change in one place

2024-02-28 17:10 UTC, crispy-wonton commented on asf_heat_pump_affordability/notebooks/Archetype_Heat_Demand.py
> +ax.set_xlabel("Total Floor Area (m2)")
```suggestion
ax.set_xlabel("Number of rooms")
```

2024-02-28 17:10 UTC, crispy-wonton commented on asf_heat_pump_affordability/notebooks/Archetype_Heat_Demand.py
> +)
I would suggest to hard-code both variables here if hard-coding one. The order of quantiles.index is defined outside this notebook so I would do this just in case the order of quantiles changes in the future.

```suggestion
# %%
archetypes = ['pre_1950_flat',
 'post_1950_flat',
 'pre_1950_semi_terraced_house',
 'post_1950_semi_terraced_house',
 'pre_1950_detached_house',
 'post_1950_detached_house',
 'pre_1950_bungalow',
 'post_1950_bungalow']

pred = (
    model.get_prediction(
        pandas.DataFrame(
            {
                "archetype": archetypes,
                "NUMBER_HABITABLE_ROOMS": [2, 2, 5, 5, 7, 7, 4, 4],
            }
        )
    )
    .summary_frame()
    .assign(
        archetype=archetypes, NUMBER_HABITABLE_ROOMS=[2, 2, 5, 5, 7, 7, 4, 4]
    )
)
```

2024-02-28 17:10 UTC, crispy-wonton commented on asf_heat_pump_affordability/notebooks/Archetype_Heat_Demand.py
> +# This model is a slightly better fit, not clear if it's worth it.
Only by about 0.4% with adding 7 features and when you run this model on archetypes + median number of rooms, it doesnt really change the results that much (about 140 kWh mean avg difference)

2024-02-29 11:16 UTC, danlewis85 commented on asf_heat_pump_affordability/notebooks/Archetype_Heat_Demand.py
> +model = sm.quantreg("heat_demand ~ archetype + NUMBER_HABITABLE_ROOMS", data=data).fit(
R-squared only really holds for linear regression as a proportion of the variance explained. For all other forms of regression pseudo R-squared is an approximation to useful properties of R-squared as a goodness of fit indicator. Because OLS delivers the conditional mean of a dependent variable by explanatory variables and hence squared deviations make up a variance from that mean, R-squared is directly applicable. Quantile regression is not solved by straightforward least squares (statsmodels uses iterative reweighted least squares), so a conventional R-squared doesn't work as the sum of square differences from the fitted line doesn't make sense as a variance.

Instead, quantile regression uses a 'pseudo R-squared' (there are lots of different ones of these dependent on model), as a familiar approximation to what R2 measures as a goodness-of-fit. Statsmodels actually creates a pseudo R-square which is a ratio of the absolute residual deviation and the absolute explained deviation, adjusted for the percentile of interest. So, it looks very similar to R-squared but isn't exactly a variance measure. See here: https://github.com/statsmodels/statsmodels/blob/26645ecc0fc0a048d5e6352e89820ecb2fa4b8f5/statsmodels/regression/quantile_regression.py#L269

2024-02-29 11:21 UTC, danlewis85 commented on asf_heat_pump_affordability/notebooks/Archetype_Heat_Demand.py
> +        NUMBER_HABITABLE_ROOMS=list(numpy.linspace(0, 12, 13)) * 8,
Have remove 0s.

2024-02-29 11:27 UTC, merged